package main.java.gui.layout;

/**
 * Mapping for the panes in the pane pool generated by the
 * LayoutManager.
 *
 * @author Janos Benyovszki
 * @see LayoutManager
 */
public interface LayoutPoolMap {

    static final int FRAME = 0;
    static final int START = 1;
    static final int TRANSACTIONS = 2;
    static final int DATA = 3;

    //TODO enum class instead of Strings - multiple strings can be mixed now

    static final String FRAME_LOCATION = "Frame.fxml";
    static final String FRAME_RESOURCE_LOCATION = "main/resources/Frame";
    static final String TRANSACTION_LOCATION = "Transactions.fxml";
    static final String TRANSACTION_RESOURCE_LOCATION = "main/resources/Transactions";
    static final String START_LOCATION = "Start.fxml";
    static final String START_RESOURCE_LOCATION = "main/resources/Start";
    static final String DATA_LOCATION = "Data.fxml";
    static final String DATA_RESOURCE_LOCATION = "main/resources/Data";

}
