package gui.layout;

/**
 * Mapping for the panes in the pane pool generated by the
 * LayoutManager.
 *
 * @author Janos Benyovszki
 * @see LayoutManager
 */
public interface LayoutPoolMap {

    static final int FRAME = 0;
    static final int START = 1;
    static final int TRANSACTIONS = 2;
    static final int DATA = 3;

    static final String FRAME_LOCATION = "Frame.fxml";
    static final String FRAME_RESOURCE_LOCATION = "gui/res/Frame";
    static final String TRANSACTION_LOCATION = "Transactions.fxml";
    static final String TRANSACTION_RESOURCE_LOCATION = "gui/res/Transactions";
    static final String START_LOCATION = "Start.fxml";
    static final String START_RESOURCE_LOCATION = "gui/res/Start";
    static final String DATA_LOCATION = "Data.fxml";

}
